name: DeRegion
main: org.debianrose.deregion.Main
version: 1.0.1
api: ["1.0.0"]
commands:
  region:
    description: Manage regions
    usage: /region <wand|create|delete|list> [name]
    permission: regionprotect.command
permissions:
  regionprotect.command:
    description: Allows using region commands
    default: true
  regionprotect.admin:
    description: Allows managing all regions
    default: op
